[project]
name = "monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "slack-sdk>=3.35.0",
    "web3>=6.0.0,<7",
]
